//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
// File:			VA_west.sqf
// Author:			Kamaradski 2014
// Contributers:	RazGriz33, Josh, Zissou and StuffedSheep
//
// 
// Drop-in Virtual Arsenal ammo-box for "Transport & Ambush" & I&A
// _K = [this] execVM "int_scripts\VA-west.sqf"; from the init of any object.
//
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

	_myBox = _this select 0;

	["AmmoboxInit",[_myBox,true]] call BIS_fnc_arsenal;


	// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
// 	Empty VA system
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

[_myBox,[true],true] call BIS_fnc_removeVirtualBackpackCargo;
[_myBox,[true],true] call BIS_fnc_removeVirtualItemCargo;
[_myBox,[true],true] call BIS_fnc_removeVirtualWeaponCargo;
[_myBox,[true],true] call BIS_fnc_removeVirtualMagazineCargo;


	
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
// 	Backpacks
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

[_myBox,[
	"B_HMG_01_F",
	"B_GMG_01_F",
	"B_HMG_01_support_F",
	"B_HMG_01_weapon_F",
	"B_GMG_01_weapon_F",
	"B_static_AA_F",
	"B_AA_01_weapon_F",
	"B_static_AT_F",
	"B_AT_01_weapon_F",
	"B_HMG_01_support_high_F",
	"B_HMG_01_high_weapon_F",
	"B_GMG_01_high_weapon_F",
	"B_GMG_01_high_F",
	"B_HMG_01_high_F",
	"B_AssaultPack_khk",
	"B_AssaultPack_khk_holder",
	"B_Fieldpack_oli_Ammo",
	"B_Fieldpack_oli_Medic",
	"B_Fieldpack_oli_Repair",
	"B_Fieldpack_oli",
	"B_AssaultPack_dgtl",
	"B_Fieldpack_oli_AAR",
	"B_AssaultPack_rgr",
	"B_AssaultPack_rgr_AT",
	"B_AssaultPack_rgr_Medic",
	"B_AssaultPack_rgr_ReconMedic",
	"B_AssaultPack_rgr_Repair",
	"B_AssaultPack_sgg",
	"B_AssaultPack_sgg_ReconExp",
	"B_AssaultPack_sgg_ReconLAT",
	"B_AssaultPack_blk",
	"B_AssaultPack_blk_DiverExp",
	"B_AssaultPack_cbr",
	"B_AssaultPack_mcamo",
	"B_AssaultPack_mcamo_AA",
	"B_AssaultPack_mcamo_AAR",
	"B_AssaultPack_mcamo_Ammo",
	"B_AssaultPack_ocamo",
	"B_Kitbag_mcamo",
	"B_Kitbag_mcamo_Eng",
	"B_Kitbag_sgg",
	"B_Kitbag_cbr",
	"B_Bergen_mcamo",
	"B_Bergen_mcamo_AAA",
	"B_Carryall_oli",
	"B_Carryall_oli_AAT",
	"B_Carryall_oli_Exp",
	"B_Carryall_oli_AAA",
	"B_Carryall_oli_Eng",
	"B_Bergen_rgr",
	"B_Bergen_rgr_AAT",
	"B_Bergen_sgg",
	"B_Bergen_sgg_Exp",
	"B_Bergen_blk",
	"B_FieldPack_khk",
	"B_FieldPack_blk",
	"B_FieldPack_blk_DiverExp",
	"B_FieldPack_ocamo",
	"B_FieldPack_ocamo_AA",
	"B_FieldPack_ocamo_AAR",
	"B_FieldPack_ocamo_Medic",
	"B_FieldPack_ocamo_ReconMedic",
	"B_FieldPack_oucamo",
	"B_FieldPack_oucamo_AAR",
	"B_FieldPack_oucamo_ReconExp",
	"B_FieldPack_ocamo_Spotter",
	"B_FieldPack_cbr",
	"B_FieldPack_cbr_AAT",
	"B_FieldPack_cbr_Ammo",
	"B_FieldPack_cbr_Repair",
	"B_Carryall_ocamo",
	"B_Carryall_ocamo_AAA",
	"B_Carryall_ocamo_Eng",
	"B_Carryall_oucamo",
	"B_Carryall_ocamo_Exp",
	"B_Carryall_khk",
	"B_Carryall_cbr",
	"B_Carryall_cbr_AAT",
	"B_OutdoorPack_blk",
	"B_OutdoorPack_tan",
	"B_OutdoorPack_blu",
	"B_HuntingBackpack",
	"B_AssaultPackG",
	"B_AssaultPackG_AAR",
	"B_AssaultPackG_Eng",
	"B_BergenG",
	"B_BergenG_Medic",
	"B_BergenC_red",
	"B_BergenC_grn",
	"B_BergenC_blu",
	"B_Parachute",
	"Bag_Base",
	"B_AssaultPack_Base",
	"B_Kitbag_Base",
	"B_Bergen_Base",
	"B_FieldPack_Base",
	"B_Carryall_Base",
	"B_OutdoorPack_Base",
	"B_BergenC_Base",
	"B_Kitbag_rgr",
	"B_TacticalPack_oli",
	"B_TacticalPack_blk",
	"B_TacticalPack_ocamo",
	"B_TacticalPack_mcamo",
	"B_TacticalPack_rgr",
	"B_Carryall_mcamo",
	"B_AssaultPack_mcamo_AT",
	"B_AssaultPack_rgr_ReconExp",
	"B_AssaultPack_rgr_ReconLAT",
	"B_Carryall_mcamo_AAA",
	"B_Carryall_mcamo_AAT",
	"B_FieldPack_cbr_AT",
	"B_FieldPack_cbr_AA",
	"B_FieldPack_cbr_AAA",
	"B_FieldPack_cbr_Medic",
	"B_FieldPack_ocamo_ReconExp",
	"B_FieldPack_cbr_RPG_AT",
	"B_FieldPack_oucamo_AT",
	"B_FieldPack_oucamo_LAT",
	"B_Carryall_oucamo_AAT",
	"B_FieldPack_oucamo_AA",
	"B_Carryall_oucamo_AAA",
	"B_FieldPack_oucamo_Medic",
	"B_FieldPack_oucamo_Ammo",
	"B_FieldPack_oucamo_Repair",
	"B_Carryall_oucamo_Exp",
	"B_Carryall_oucamo_Eng"
	],true] call BIS_fnc_addVirtualBackpackCargo;



	
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
// 	Items
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

[_myBox,[
	"G_Aviator",
	"G_Balaclava_blk",
	"G_balaclava_combat",
	"G_Balaclava_lowprofile",
	"G_Balaclava_oli",
	"G_Bandanna_aviator",
	"G_Bandanna_beast",
	"G_Bandanna_blk",
	"G_Bandanna_khk",
	"G_Bandanna_oli",
	"G_Bandanna_shades",
	"G_Bandanna_sport",
	"G_Bandanna_tan",
	"G_Combat",
	"G_Diving",
	"G_Lowprofile",
	"G_Shades_Black",
	"G_Shades_Blue",
	"G_Shades_Green",
	"G_Shades_Red",
	"G_Spectacles",
	"G_Spectacles_Tinted",
	"G_Sport_Blackred",
	"G_Sport_Blackyellow",
	"G_Sport_Checkered",
	"G_Sport_Greenblack",
	"G_Sport_Red",
	"G_Squares",
	"G_Squares_Tinted",
	"G_Tactical_Black",
	"G_Tactical_Clear",
	"U_B_CombatUniform_wdl",
	"U_B_CombatUniform_wdl_tshirt",
	"U_B_CombatUniform_wdl_vest",
	"U_B_CombatUniform_sgg",
	"U_B_CombatUniform_sgg_tshirt",
	"U_B_CombatUniform_sgg_vest",
	"U_BG_leader",
	"U_BG_Guerilla3_2",
	"U_BG_Guerilla3_1",
	"U_BG_Guerilla2_3",
	"U_BG_Guerilla2_2",
	"U_BG_Guerilla2_1",
	"U_BG_Guerilla1_1",
	"U_B_CTRG_1",
	"U_B_CTRG_2",
	"U_B_CTRG_3",
	"U_B_survival_uniform",
	"U_BasicBody",
	"U_B_CombatUniform_mcam",
	"U_B_CombatUniform_mcam_worn",
	"U_B_CombatUniform_mcam_tshirt",
	"U_B_CombatUniform_mcam_vest",
	"U_B_SpecopsUniform_sgg",
	"U_B_GhillieSuit",
	"U_B_HeliPilotCoveralls",
	"U_B_PilotCoveralls",
	"U_B_Wetsuit",
	"Rangefinder",
	"Laserdesignator_mounted",
	"SmokeLauncher",
	"FlareLauncher",
	"CMFlareLauncher",
	"ItemWatch",
	"ItemCompass",
	"ItemGPS",
	"ItemRadio",
	"ItemMap",
	"MineDetector",
	"NVGoggles",
	"NVGoggles_OPFOR",
	"NVGoggles_INDEP",
	"Laserdesignator",
	"FirstAidKit",
	"Medikit",
	"ToolKit",
	"U_Rangemaster",
	"V_Rangemaster_belt",
	"V_BandollierB_khk",
	"V_BandollierB_rgr",
	"V_BandollierB_cbr",
	"V_PlateCarrier1_rgr",
	"V_PlateCarrier1_blk",
	"V_PlateCarrier2_rgr",
	"V_PlateCarrier3_rgr",
	"V_PlateCarrierGL_rgr",
	"V_PlateCarrierSpec_rgr",
	"V_Chestrig_khk",
	"V_TacVest_khk",
	"V_TacVest_brn",
	"V_TacVest_blk",
	"V_TacVest_camo",
	"V_TacVest_oli",
	"V_TacVest_blk_POLICE",
	"V_TacVestIR_blk",
	"V_HarnessO_brn",
	"V_HarnessO_gry",
	"V_HarnessOGL_brn",
	"V_HarnessOGL_gry",
	"V_HarnessOSpec_brn",
	"V_HarnessOSpec_gry",
	"V_TacVestCamo_khk",
	"V_PlateCarrierIA1_dgtl",
	"V_PlateCarrierIA2_dgtl",
	"V_PlateCarrierIAGL_dgtl",
	"V_RebreatherB",
	"V_RebreatherIR",
	"V_RebreatherIA",
	"H_HelmetB",
	"H_Booniehat_khk",
	"H_Booniehat_mcamo",
	"H_Booniehat_grn",
	"H_Booniehat_tan",
	"H_Booniehat_dirty",
	"H_Booniehat_dgtl",
	"H_HelmetB_paint",
	"H_HelmetB_light",
	"H_HelmetB_plain_mcamo",
	"H_HelmetB_plain_blk",
	"H_HelmetCrew_B",
	"H_HelmetCrew_O",
	"H_HelmetCrew_I",
	"H_HelmetSpecB",
	"H_HelmetSpecB_paint1",
	"H_HelmetSpecB_paint2",
	"H_HelmetSpecB_blk",
	"H_HelmetIA",
	"H_Cap_red",
	"H_Cap_tan",
	"H_Cap_blk",
	"H_Cap_blk_CMMG",
	"H_Cap_brn_SPECOPS",
	"H_Cap_tan_specops_US",
	"H_Cap_khaki_specops_UK",
	"H_Cap_grn",
	"H_Cap_grn_BI",
	"H_Cap_blu",
	"H_Cap_blk_Raven",
	"H_Cap_blk_ION",
	"H_Cap_headphones",
	"H_PilotHelmetFighter_B",
	"H_PilotHelmetFighter_O",
	"H_PilotHelmetFighter_I",
	"H_PilotHelmetHeli_B",
	"H_PilotHelmetHeli_O",
	"H_PilotHelmetHeli_I",
	"H_CrewHelmetHeli_B",
	"H_CrewHelmetHeli_O",
	"H_CrewHelmetHeli_I",
	"H_BandMask_blk",
	"H_BandMask_khk",
	"H_BandMask_reaper",
	"H_BandMask_demon",
	"H_HelmetO_ocamo",
	"H_HelmetO_oucamo",
	"H_HelmetSpecO_ocamo",
	"H_HelmetSpecO_blk",
	"H_MilCap_ocamo",
	"H_MilCap_oucamo",
	"H_MilCap_rucamo",
	"H_MilCap_mcamo",
	"H_MilCap_gry",
	"H_MilCap_dgtl",
	"H_MilCap_blue",
	"H_Bandanna_surfer",
	"H_Bandanna_khk",
	"H_Bandanna_cbr",
	"H_Bandanna_sgg",
	"H_Bandanna_gry",
	"H_Bandanna_camo",
	"H_Bandanna_mcamo",
	"H_Shemag_khk",
	"H_Shemag_tan",
	"H_ShemagOpen_khk",
	"H_ShemagOpen_tan",
	"H_Beret_blk",
	"H_Beret_blk_POLICE",
	"H_Beret_red",
	"H_Beret_grn",
	"H_Beret_grn_SF",
	"H_Beret_brn_SF",
	"H_Watchcap_blk",
	"H_Watchcap_khk",
	"H_Watchcap_camo",
	"H_Watchcap_sgg",
	"H_TurbanO_blk",
	"H_StrawHat",
	"H_StrawHat_dark",
	"H_Hat_blue",
	"H_Hat_brown",
	"H_Hat_camo",
	"H_Hat_grey",
	"H_Hat_checker",
	"H_Hat_tan",
	"V_BandollierB_blk",
	"V_Chestrig_rgr",
	"V_Chestrig_blk",
	"H_HelmetB_camo",
	"H_Booniehat_indp",
	"H_Cap_oli",
	"H_HelmetLeaderO_ocamo",
	"U_B_CombatUniform_wdl",
	"U_B_CombatUniform_wdl_tshirt",
	"U_B_CombatUniform_wdl_vest",
	"U_B_CombatUniform_sgg",
	"U_B_CombatUniform_sgg_tshirt",
	"U_B_CombatUniform_sgg_vest",
	"U_I_HeliPilotCoveralls",
	"U_I_OfficerUniform",
	"U_Competitor",
	"U_OI_Scientist",
	"V_BandollierB_oli",
	"V_Chestrig_oli",
	"H_HelmetIA_net",
	"H_HelmetIA_camo",
	"H_HelmetLeaderO_oucamo",
	"H_Shemag_olive",
	"H_Beret_ocamo",
	"U_OG_leader",
	"U_OG_Guerilla3_2",
	"U_OG_Guerilla3_1",
	"U_OG_Guerilla2_3",
	"U_OG_Guerilla2_2",
	"U_OG_Guerilla2_1",
	"U_OG_Guerilla1_1",
	"U_BG_leader",
	"U_BG_Guerilla3_2",
	"U_BG_Guerilla3_1",
	"U_BG_Guerilla2_3",
	"U_BG_Guerilla2_2",
	"U_BG_Guerilla2_1",
	"U_BG_Guerilla1_1",
	"U_IG_leader",
	"U_IG_Guerilla2_3",
	"muzzle_snds_H",
	"muzzle_snds_L",
	"muzzle_snds_B",
	"muzzle_snds_H_MG",
	"optic_Arco",
	"optic_Hamr",
	"optic_Aco",
	"optic_ACO_grn",
	"optic_Holosight",
	"optic_NVS",
	"optic_Nightstalker",
	"optic_SOS",
	"optic_MRCO",
	"optic_tws",
	"optic_tws_mg",
	"acc_flashlight",
	"acc_pointer_IR",
	"U_B_CTRG_1",
	"U_B_CTRG_2",
	"U_B_CTRG_3",
	"U_B_survival_uniform",
	"V_PlateCarrier_Kerry",
	"V_PlateCarrierL_CTRG",
	"V_PlateCarrierH_CTRG",
	"H_HelmetB_light_sand",
	"H_HelmetB_light_black",
	"H_HelmetB_light_desert",
	"H_HelmetB_light_snakeskin",
	"H_HelmetB_light_grass",
	"H_HelmetB_sand",
	"H_HelmetB_black",
	"H_HelmetB_desert",
	"H_HelmetB_snakeskin",
	"H_HelmetB_grass",
	"H_Helmet_Kerry",
	"U_I_G_Story_Protagonist_F",
	"U_I_G_resistanceLeader_F",
	"V_I_G_resistanceLeader_F",
	"H_Booniehat_khk_hs",
	"H_Bandanna_khk_hs",
	"H_Cap_oli_hs",
	"H_Shemag_olive_hs",
	"H_Beret_02",
	"U_C_Journalist",
	"U_C_Scientist",
	"V_Press_F",
	"H_Beret_Colonel",
	"B_UavTerminal",
	"H_Cap_press",
	"U_NikosAgedBody",
	"H_Cap_marshal",
	"U_Marshal",
	"muzzle_snds_acp",
	"muzzle_snds_M",
	"optic_Yorris",
	"optic_MRD",
	"optic_Aco_smg",
	"optic_ACO_grn_smg",
	"optic_Holosight_smg",
	"optic_DMS",
	"optic_LRPS"
	],true] call BIS_fnc_addVirtualItemCargo;





// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
// 	Weapons
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

[_myBox,[
	"launch_NLAW_F",
	"srifle_EBR_F",
	"srifle_EBR_SOS_F",
	"srifle_EBR_ACO_F",
	"srifle_EBR_ARCO_pointer_F",
	"srifle_EBR_MRCO_pointer_F",
	"srifle_GM6_F",
	"srifle_GM6_camo_F",
	"srifle_GM6_SOS_F",
	"srifle_GM6_camo_SOS_F",
	"srifle_LRR_F",
	"srifle_LRR_camo_F",
	"srifle_LRR_SOS_F",
	"srifle_LRR_camo_SOS_F",
	"LMG_Mk200_F",
	"LMG_Mk200_MRCO_F",
	"LMG_Mk200_pointer_F",
	"hgun_P07_F",
	"hgun_P07_snds_F",
	"hgun_Rook40_F",
	"hgun_Rook40_snds_F",
	"arifle_Katiba_F",
	"arifle_Katiba_C_F",
	"arifle_Katiba_GL_F",
	"arifle_Katiba_C_ACO_pointer_F",
	"arifle_Katiba_C_ACO_F",
	"arifle_Katiba_ACO_F",
	"arifle_Katiba_ACO_pointer_F",
	"arifle_Katiba_ARCO_F",
	"arifle_Katiba_ARCO_pointer_F",
	"arifle_Katiba_GL_ACO_F",
	"arifle_Katiba_GL_ARCO_pointer_F",
	"arifle_Katiba_GL_ACO_pointer_F",
	"arifle_MXC_F",
	"arifle_MX_F",
	"arifle_MX_GL_F",
	"arifle_MX_SW_F",
	"arifle_MXM_F",
	"arifle_MX_Hamr_pointer_F",
	"arifle_MX_ACO_pointer_F",
	"arifle_MX_GL_ACO_pointer_F",
	"arifle_MX_GL_Hamr_pointer_F",
	"arifle_MXC_Holo_F",
	"arifle_MXC_Holo_pointer_F",
	"arifle_MX_SW_Hamr_pointer_F",
	"arifle_MXM_Hamr_pointer_F",
	"arifle_MX_pointer_F",
	"arifle_MX_Holo_pointer_F",
	"arifle_MX_ACO_F",
	"arifle_MX_GL_ACO_F",
	"arifle_MX_SW_pointer_F",
	"arifle_SDAR_F",
	"arifle_TRG21_F",
	"arifle_TRG20_F",
	"arifle_TRG21_GL_F",
	"arifle_TRG20_Holo_F",
	"arifle_TRG20_ACO_pointer_F",
	"arifle_TRG20_ACO_F",
	"arifle_TRG20_ACO_Flash_F",
	"arifle_TRG21_ARCO_pointer_F",
	"arifle_TRG21_GL_ACO_pointer_F",
	"arifle_TRG21_ACO_pointer_F",
	"arifle_TRG21_MRCO_F",
	"arifle_TRG21_GL_MRCO_F",
	"launch_Titan_F",
	"launch_Titan_short_F",
	"launch_B_Titan_F",
	"launch_I_Titan_F",
	"launch_O_Titan_F",
	"launch_B_Titan_short_F",
	"launch_I_Titan_short_F",
	"launch_O_Titan_short_F",
	"LMG_Zafir_F",
	"LMG_Zafir_pointer_F",
	"hgun_ACPC2_F",
	"hgun_ACPC2_snds_F",
	"arifle_Mk20_F",
	"arifle_Mk20C_F",
	"arifle_Mk20_GL_F",
	"arifle_Mk20C_ACO_F",
	"arifle_Mk20_Holo_F",
	"arifle_Mk20_ACO_F",
	"arifle_Mk20_plain_F",
	"arifle_Mk20C_plain_F",
	"arifle_Mk20_GL_plain_F",
	"arifle_Mk20C_ACO_pointer_F",
	"arifle_Mk20_pointer_F",
	"arifle_Mk20_ACO_pointer_F",
	"arifle_Mk20_MRCO_F",
	"arifle_Mk20_MRCO_plain_F",
	"arifle_Mk20_MRCO_pointer_F",
	"arifle_Mk20_GL_MRCO_pointer_F",
	"arifle_Mk20_GL_ACO_F",
	"SMG_01_F",
	"SMG_01_Holo_F",
	"SMG_01_Holo_pointer_snds_F",
	"SMG_01_ACO_F",
	"SMG_02_F",
	"SMG_02_ACO_F",
	"SMG_02_ARCO_pointg_F",
	"srifle_DMR_01_F",
	"srifle_DMR_01_SOS_F",
	"srifle_DMR_01_ACO_F",
	"srifle_DMR_01_DMS_F",
	"srifle_EBR_F",
	"srifle_EBR_SOS_F",
	"srifle_EBR_ACO_F",
	"srifle_EBR_ARCO_pointer_F",
	"srifle_EBR_DMS_F",
	"srifle_EBR_Hamr_pointer_F",
	"srifle_EBR_DMS_pointer_snds_F",
	"srifle_GM6_F",
	"srifle_GM6_SOS_F",
	"hgun_Pistol_heavy_01_F",
	"hgun_Pistol_heavy_01_snds_F",
	"hgun_Pistol_heavy_01_MRD_F",
	"hgun_Pistol_heavy_02_F",
	"hgun_Pistol_heavy_02_Yorris_F",
	"srifle_GM6_F",
	"srifle_GM6_LRPS_F",
	"srifle_LRR_F",
	"srifle_LRR_LRPS_F",
	"arifle_MX_SW_Black_Hamr_pointer_F",
	"arifle_MX_Black_Hamr_pointer_F",
	"arifle_MX_GL_Black_Hamr_pointer_F",
	"arifle_MXM_Black_F",
	"arifle_MX_SW_Black_F",
	"arifle_MX_GL_Black_F",
	"arifle_MX_Black_F",
	"arifle_MXC_Black_F",
	"hgun_PDW2000_F",
	"hgun_PDW2000_snds_F",
	"hgun_PDW2000_Holo_snds_F",
	"hgun_PDW2000_Holo_F",
	"hgun_Pistol_Signal_F"
	],true] call BIS_fnc_addVirtualWeaponCargo;


// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
// 	Ammunition
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
	
[_myBox,[true],true] call BIS_fnc_addVirtualMagazineCargo;



// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
// 	Exclusions
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

[_myBox,[
	"LMG_Zafir_F",
	"LMG_Zafir_pointer_F",
	"arifle_Katiba_F",
	"arifle_Katiba_C_F",
	"arifle_Katiba_GL_F",
	"arifle_Katiba_C_ACO_pointer_F",
	"arifle_Katiba_C_ACO_F",
	"arifle_Katiba_ACO_F",
	"arifle_Katiba_ACO_pointer_F",
	"arifle_Katiba_ARCO_F",
	"arifle_Katiba_ARCO_pointer_F",
	"arifle_Katiba_GL_ACO_F",
	"arifle_Katiba_GL_ARCO_pointer_F",
	"arifle_Katiba_GL_ACO_pointer_F",
	"srifle_DMR_01_F",
	"srifle_DMR_01_SOS_F",
	"srifle_DMR_01_ACO_F",
	"srifle_DMR_01_DMS_F"
	],true] call BIS_fnc_removeVirtualWeaponCargo;
	
	